### PR TITLE
Prevent MSVC displaying .c filename when compiling

### PR DESCRIPTION
**Pull request by dra27**
See also https://github.com/ocaml/ocaml/pull/407.

### CODE REVIEW

**Comment by alainfrisch** [comment]
Thanks!

**Comment by dra27** [comment]
Ah - we're working too quickly - something's failing in the testsuite run... give me a minute!

**Comment by dra27** [comment]
(sorry, I thought enough of the testsuite had run...)

**Comment by alainfrisch** [comment]
Is that a problem with the PR on flexdll, or the one in OCaml?

**Comment by dra27** [comment]
This one on FlexDLL - I accidentally shadowed a variable, but it doesn't pick up when building OCaml because it never exercise ocamlc -custom

**Comment by dra27** [comment]
I'm just (properly) testing the actual fix - do you want me to push an additional PR, or will you reset to HEAD~1 on master (never thought I'd write that!)

**Comment by alainfrisch** [comment]
I prefer an additional PR.

**Comment by dra27** [comment]
OK - immortalise my embarrassing errors, why don't you :wink: It's done - but I'm allowing a full testsuite run before opening the PR this time!

**Pull request merged**
