### PR TITLE
Fix errors in previous attempt to silence MSVC

### PR DESCRIPTION
**Pull request by dra27**
Correct fix this time!

### CODE REVIEW

**Comment by alainfrisch** [comment]
Is it intentional to not show the content of the redirected stdout in case of error?

**Comment by dra27** [comment]
No!

**Comment by dra27** [comment]
That should deal with that (I'm just about to run it) - but one other question. I don't think it's my regression, but in dry_mode, should it be compiling the file??

**Comment by alainfrisch** [comment]
> but in dry_mode, should it be compiling the file??

No, of course!

**Comment by dra27** [comment]
I wasn't sure, given how that it works - in which case, I'll fix that while I'm here!

**Comment by dra27** [comment]
There we go - that should fix that too. x86 and x64 builds and testsuite presently running...

**Comment by dra27** [comment]
That all seems to be fine

**Comment by alainfrisch** [comment]
Thanks!

**Pull request merged**
